-- DEL-34 — Add `campaign_invitations` table (schema + RLS + token).
--
-- Invitations are durable, first-class entities with a state machine — not
-- transient feed items. They cover two distinct invite flows:
--
--   1. Existing-user invite. Handler picks a known user by id; the row has
--      `invitee_user_id` set and `invitee_email`/`token` null. The invitee
--      sees the invitation in-app (notifications inbox / DEL-46 accept flow).
--
--   2. Stranger / magic-link invite. Handler enters an email address that
--      doesn't match any existing user; the row has `invitee_email` set,
--      `invitee_user_id` null, and a single-use `token` generated by the
--      `set_invitation_token` trigger below. An emailed magic link of the
--      form `https://<app>/invite/:token` (DEL-45) lands the recipient on a
--      page that resolves the token via the public security-definer RPC
--      `get_invitation_by_token`, then routes them into signup with the
--      invited email pre-filled. On successful signup, the app patches
--      `invitee_user_id` and runs the accept flow (DEL-46).
--
-- A `CHECK` constraint enforces "exactly one of `invitee_user_id` /
-- `invitee_email`" — XOR, not OR. Token is generated server-side by a
-- `BEFORE INSERT` trigger for email-only invites and is otherwise left null,
-- so the table client doesn't have to remember the rule.
--
-- Two partial unique indexes (`where status = 'pending'`) prevent duplicate
-- open invites to the same person for the same campaign. The status flips
-- to `revoked` / `accepted` / `declined` / `expired` over the invitation
-- lifecycle and the partial unique releases, so a fresh invite can be sent
-- to the same target later. State transitions are owned by the application
-- layer — no DB-side state machine enforcement.
--
-- No periodic expiry sweep. Queries filter `status = 'pending' and
-- expires_at > now()`. The stored status stays `pending` until someone
-- tries to act on it. A cron-based sweep can be added later if needed.
--
-- RLS model:
--   - Handler of the campaign (GM) can read/insert/update/delete invitations
--     for their campaign. Delete is allowed but the app SHOULD prefer the
--     `revoked` status flip for normal "cancel this invite" actions so
--     audit history is preserved (and so the notifications triggers added
--     in DEL-35 can fan out on the status change). Hard DELETE is the
--     "clean up old history" lever, not the default cancel button.
--   - Existing-user invitee (when `invitee_user_id = auth.uid()`) can
--     read and update their own invitation row — accept / decline.
--   - Stranger / magic-link reads are NOT routed through RLS at all. The
--     `campaign_invitations` table stays inaccessible to `anon`; the only
--     public surface is the `get_invitation_by_token` security-definer
--     RPC below, which returns the minimum fields the accept page needs
--     and nothing else.
--
-- Helpers `is_campaign_member(uuid)` and `is_campaign_gm(uuid)` are defined
-- in the initial schema migration; no new helpers are introduced here.

-- ============================================================
-- TABLE
-- ============================================================

create table campaign_invitations (
  id              uuid primary key default gen_random_uuid(),
  campaign_id     uuid not null references campaigns(id) on delete cascade,
  invited_by      uuid not null references auth.users(id) on delete cascade,
  invitee_user_id uuid references auth.users(id) on delete cascade,
  invitee_email   text,
  -- `unique` here creates a btree index on token, used by the magic-link
  -- RPC below for `where token = $1` lookups. No separate `create index`
  -- on token is needed.
  token           text unique,
  message         text,
  status          text not null default 'pending',
  expires_at      timestamptz not null default (now() + interval '7 days'),
  created_at      timestamptz not null default now(),
  resolved_at     timestamptz,

  constraint campaign_invitations_status_valid check (status in (
    'pending',
    'accepted',
    'declined',
    'revoked',
    'expired'
  )),

  -- Exactly one of `invitee_user_id` or `invitee_email` must be set. XOR,
  -- not OR — an invite is either to a known user or to an email, never both.
  constraint campaign_invitations_invitee_xor check (
    (invitee_user_id is not null) <> (invitee_email is not null)
  )
);

-- Lookup-direction indexes (DoD).
create index campaign_invitations_campaign_id_idx
  on campaign_invitations(campaign_id);
create index campaign_invitations_invitee_user_id_idx
  on campaign_invitations(invitee_user_id);
create index campaign_invitations_invitee_email_idx
  on campaign_invitations(invitee_email);

-- Partial unique indexes prevent duplicate OPEN invites to the same person
-- for the same campaign. Once an invite moves out of `pending` the slot
-- frees up so a fresh invite is allowed.
create unique index campaign_invitations_pending_user_uidx
  on campaign_invitations(campaign_id, invitee_user_id)
  where status = 'pending';

create unique index campaign_invitations_pending_email_uidx
  on campaign_invitations(campaign_id, invitee_email)
  where status = 'pending';

-- ============================================================
-- ENABLE ROW LEVEL SECURITY
-- ============================================================

alter table campaign_invitations enable row level security;

-- ============================================================
-- TABLE-DEPENDENT HELPER FUNCTIONS
-- ============================================================

-- Generate a single-use hex token for email-only invites. Existing-user
-- invites leave `token` null even if a caller passes one in, so the rule
-- "tokens exist only for stranger invites" is enforced at the DB.
create or replace function set_invitation_token()
returns trigger language plpgsql as $$
begin
  if new.invitee_email is not null then
    -- 24 random bytes → 48 hex chars → 192 bits of entropy. Plenty for a
    -- single-use magic-link token, URL-safe without further encoding.
    if new.token is null then
      new.token := encode(gen_random_bytes(24), 'hex');
    end if;
  else
    new.token := null;
  end if;
  return new;
end;
$$;

-- ============================================================
-- POLICIES
-- ============================================================

-- Handler: full read on invitations for their campaign(s).
create policy "campaign_invitations: gm can read"
  on campaign_invitations for select
  using (is_campaign_gm(campaign_id));

-- Existing-user invitee: read their own pending / resolved invitations.
-- Stranger / magic-link reads are NOT covered by RLS — they go through
-- `get_invitation_by_token` below.
create policy "campaign_invitations: invitee can read own"
  on campaign_invitations for select
  using (invitee_user_id = auth.uid());

-- Handler: insert invitations into campaigns they GM. The `with check`
-- also requires `invited_by = auth.uid()` so a GM can't ghost-write
-- another user as the inviter.
create policy "campaign_invitations: gm can insert"
  on campaign_invitations for insert
  with check (
    is_campaign_gm(campaign_id)
    and invited_by = auth.uid()
  );

-- Handler: update invitations on their campaign(s). Used for status flips
-- (revoke, expire) and message edits.
create policy "campaign_invitations: gm can update"
  on campaign_invitations for update
  using (is_campaign_gm(campaign_id))
  with check (is_campaign_gm(campaign_id));

-- Existing-user invitee: update their own invitation row — accept /
-- decline. The DB doesn't constrain WHICH status the invitee can move to;
-- the app layer is responsible for the valid transition set (the trigger
-- plumbing in DEL-35 will also fire on these status changes). The
-- `with check` keeps the invitee from re-assigning the row to someone
-- else via the update.
create policy "campaign_invitations: invitee can update own"
  on campaign_invitations for update
  using (invitee_user_id = auth.uid())
  with check (invitee_user_id = auth.uid());

-- Handler: hard-delete an invitation. Prefer the `revoked` status flip
-- for normal cancellation — it preserves audit history (members-screen
-- counts in DEL-44, accept/decline notifications in DEL-35). Hard DELETE
-- is the "clean up old history" lever, not the default cancel button. No
-- DELETE policy for invitees by design — declining is a status flip.
create policy "campaign_invitations: gm can delete"
  on campaign_invitations for delete
  using (is_campaign_gm(campaign_id));

-- ============================================================
-- TRIGGERS
-- ============================================================

create trigger campaign_invitations_set_token
  before insert on campaign_invitations
  for each row execute function set_invitation_token();

-- ============================================================
-- PUBLIC RPC: get_invitation_by_token
-- ============================================================
--
-- The only public surface for unauthenticated invite-link visits. Used by
-- DEL-45's `/invite/:token` route to render the accept screen before the
-- recipient has signed in (or signed up, in the stranger flow).
--
-- Returns only the minimum fields the accept page needs: campaign name,
-- inviter handle (display_name from user_metadata if set, else the email
-- local-part — no email exposure), invitation status, expiry, message,
-- and the invitee_email so the signup page can pre-fill it. Internal
-- columns (`id`, `invited_by`, `invitee_user_id`, `resolved_at`, …) are
-- never returned.
--
-- Filters `invitee_email is not null` so the magic-link flow can only
-- read stranger invites — even if a caller somehow guesses a token belonging
-- to an existing-user invite, it won't resolve here. Returns zero rows
-- for unknown / non-stranger tokens; the caller treats empty as "invalid".
--
-- Does NOT pre-filter `status` or `expires_at` — the caller (DEL-45)
-- needs the actual status and expiry to render the correct
-- `InviteGoneScreen` variant (`pending` vs `expired` vs `revoked` vs
-- `accepted` vs `declined`).
--
-- `security definer` + explicit `search_path` prevents the standard
-- search-path attack; the function runs as its owner regardless of the
-- caller's role and resolves `campaign_invitations`, `campaigns`, and
-- `auth.users` from the locked-down path.
create or replace function get_invitation_by_token(p_token text)
returns table (
  campaign_name  text,
  inviter_handle text,
  status         text,
  expires_at     timestamptz,
  message        text,
  invitee_email  text
)
language sql security definer stable
set search_path = public, auth
as $$
  select
    c.name                                                  as campaign_name,
    coalesce(
      nullif(u.raw_user_meta_data->>'display_name', ''),
      split_part(u.email, '@', 1)
    )                                                       as inviter_handle,
    ci.status,
    ci.expires_at,
    ci.message,
    ci.invitee_email
  from campaign_invitations ci
  join campaigns c   on c.id = ci.campaign_id
  join auth.users u  on u.id = ci.invited_by
  where ci.token = p_token
    and ci.invitee_email is not null;
$$;

-- Both `anon` and `authenticated` may call the RPC. Anon covers the
-- not-yet-signed-up stranger case; authenticated covers the "logged-in
-- but with a different email than invited" recovery branch in DEL-45.
grant execute on function get_invitation_by_token(text) to anon, authenticated;
